version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: todo_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/tododb
      PORT: 3000
      SECRET_KEY: your_secret_key_here
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node server.js
    ports:
      - "3000:3000"

volumes:
  db_data:
